version: '3'
services:
  mysql-standalone:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=imageclassification
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

    volumes:
    - imageclassificationbackend:/var/lib/mysql

  spring-boot:
    image: imageclassification-main-microservice
    ports:
      [8080:8080]
    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
        - mysql-standalone

volumes:
  imageclassificationbackend: